services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    restart: always

    ports:
      - "33432:5432"
    # expose:
    #   - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend_network

  postgres-test:
    image: postgres:16-alpine
    env_file:
      - .env.test
    restart: "no"

    ports:
      - "25439:5432"

    tmpfs:
      - /var/lib/postgresql/data

    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # OPTIONAL: pgbouncer (production)
  # pgbouncer:
  #   image: pgbouncer/pgbouncer:latest
  #   restart: always
  #   profiles: ["db"]

  #   environment:
  #     DATABASES_HOST: postgres
  #     DATABASES_PORT: 5432
  #     DATABASES_DBNAME: ${POSTGRES_DB}
  #     DATABASES_USER: ${POSTGRES_USER}
  #     DATABASES_PASSWORD: ${POSTGRES_PASSWORD}

  #   ports:
  #     - "6432:6432"

  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  #   networks:
  #     - backend_network

volumes:
  pg_data:
    driver: local

networks:
  backend_network:
    driver: bridge
