version: "3"

vars:
  RUNNER:
    sh: 'echo {{ .RUNNER | default "uv run --no-sync" }}'
  SOURCES: src tests
  SOURCES_ROOT: src

  COMPOSE_BASE: docker-compose.yml
  COMPOSE_DB: docker-compose.db.yml
  COMPOSE_OBS: docker-compose.obs.yml
  COMPOSE_WORKER: docker-compose.worker.yml

tasks:
  default:
    cmd: task --list

  ###### DATABASE ######
  db-up:
    desc: Start database container
    cmd: docker compose -f {{.COMPOSE_DB}} up -d --wait postgres

  db-down:
    desc: Stop database container
    cmd: docker compose -f {{.COMPOSE_DB}} down

  db-migrate:
    desc: Apply database migrations
    cmds:
      - task: db-up
      - "{{.RUNNER}} alembic -c src/alembic.ini upgrade head"

  db-revision:
    desc: Generate new migration
    cmds:
      - task: db-up
      - "{{.RUNNER}} alembic -c src/alembic.ini revision --autogenerate -m '{{.MSG}}'"

  db-reset:
    desc: Reset DB (local only)
    env:
      ENV: local
    cmds:
      - docker compose -f {{.COMPOSE_DB}} down -v postgres || true
      - task: db-up
      - "{{.RUNNER}} alembic -c src/alembic.ini upgrade head"

  db-shell:
    cmd: docker compose -f {{.COMPOSE_DB}} exec postgres sh -c 'psql -U $POSTGRES_USER $POSTGRES_DB'

  ###### DEVELOPMENT & RUNNING ######
  init:
    desc: Init project
    env:
      ENV: local
    cmds:
      - uv sync
      - task: db-up
      - task: db-migrate

  dev:
    desc: Run backend locally
    env:
      ENV: local
    cmds:
      - task: db-up
      - task: db-migrate
      - "{{.RUNNER}} uvicorn src.dev:app --reload --reload-dir src"

  ###### DOCKER STACKS ######
  up:
    desc: Run core infrastructure (web + db)
    cmd: docker compose -f {{.COMPOSE_BASE}} -f {{.COMPOSE_DB}} up -d

  prod:
    desc: Run production (core)
    cmds:
      - docker compose -f {{.COMPOSE_BASE}} -f {{.COMPOSE_DB}} up --build
      - docker compose ps

  obs:
    desc: Start monitoring stack (optional)
    cmd: docker compose \
      -f {{.COMPOSE_BASE}} \
      -f {{.COMPOSE_DB}} \
      -f {{.COMPOSE_OBS}} \
      up -d

  workers:
    desc: Run workers
    cmd: docker compose \
      -f {{.COMPOSE_BASE}} \
      -f {{.COMPOSE_DB}} \
      -f {{.COMPOSE_WORKER}} \
      up -d

  full:
    desc: run full stack (core + monitoring + workers)
    cmd: docker compose \
      -f {{.COMPOSE_BASE}} \
      -f {{.COMPOSE_DB}} \
      -f {{.COMPOSE_OBS}} \
      -f {{.COMPOSE_WORKER}} \
      up -d

  stack:
    desc: Full stack + migrate
    cmds:
      - task: full
      - task: db-migrate

  down:
    desc: Stop all containers
    cmd: docker compose down

  restart:
    desc: Restart all
    cmds:
      - task: down
      - task: full

  ###### WORKERS REDIS & RABBITMQ ######
  workers-redis:
    cmd: docker compose \
      -f docker-compose.yml \
      -f docker-compose.db.yml \
      -f docker-compose.worker.yml \
      --profile redis up -d

  workers-rabbitmq:
    cmd: docker compose \
      -f docker-compose.yml \
      -f docker-compose.db.yml \
      -f docker-compose.worker.yml \
      --profile rabbitmq up -d

  ###### LOGS & DEBUGGING ######
  logs:
    desc: All logs (tail 100)
    cmd: docker compose logs -f --tail=100

  logs-web:
    desc: Show logs (backend only)
    cmd: docker compose logs -f web

  logs-db:
    desc: Show logs (postgres only)
    cmd: docker compose -f {{.COMPOSE_DB}} logs -f postgres

  doctor:
    desc: Check services
    cmds:
      - docker compose ps
      - docker compose top

  ###### TESTING #######
  test-setup:
    cmds:
      - docker compose -f {{.COMPOSE_DB}} down -v postgres-test || true
      - docker compose -f {{.COMPOSE_DB}} up -d --wait postgres-test

  test:
    desc: Run unit tests
    env:
      ENV: test
    cmds:
      - task: test-setup
      - ENV=test {{.RUNNER}} pytest -vv

  test-cov:
    desc: Coverage report for tests (fail if under 75%)
    env:
      ENV: test
    cmds:
      - task: test-setup
      - "{{.RUNNER}} coverage run -m pytest -vv"
      - "{{.RUNNER}} coverage report -m --fail-under=75"

  ###### QUALITY CHECKS ######
  lint:
    desc: Run linter (ruff check)
    cmd: "{{.RUNNER}} ruff check {{.SOURCES}}"

  format:
    desc: Format code with ruff
    aliases: [fmt]
    cmds:
      - "{{.RUNNER}} ruff format {{.SOURCES}}"
      - "{{.RUNNER}} ruff check --fix {{.SOURCES}}"

  deps:
    desc: Check dependencies (deptry)
    cmd: "{{.RUNNER}} deptry {{.SOURCES_ROOT}}"

  typecheck:
    desc: Type checking (mypy)
    cmd: "{{.RUNNER}} mypy src tests"

  security:
    desc: Security scan (bandit)
    cmd: "{{.RUNNER}} bandit -r src -q"

  imports:
    desc: Check import sorting
    cmd: "{{.RUNNER}} ruff check --select I {{.SOURCES}}"

  ###### PRE-COMMIT ######
  pre-commit:
    desc: Run pre-commit
    cmd: uvx pre-commit run

  ###### DOCKER BUILD ######
  build:
    desc: Check docker build
    cmd: docker compose -f {{.COMPOSE_BASE}} -f {{.COMPOSE_DB}} build --no-cache

  ###### CI TASKS ######
  all:
    cmds:
      - task: format
      - task: deps
      - task: typecheck
      - task: test-cov

  test-ci:
    desc: CI pipline (no formatting)
    cmds:
      - task: lint
      - task: imports
      - task: deps
      - task: typecheck
      - task: security
      - task: test-cov
