"""update password reset

Revision ID: be58262522f0
Revises: 4197972909a9
Create Date: 2026-03-13 10:52:18.871126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be58262522f0'
down_revision: Union[str, None] = '4197972909a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('password_resets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_resets', 'updated_at')
    op.drop_column('password_resets', 'created_at')
    # ### end Alembic commands ###
